### ISSUE TITLE
Foreman-installer 1.11 does not know this plugin

### ISSUE THREAD

**Issue by HyperBaton** [theforeman/foreman_memcache#9]
I tried installing this plugin with foreman-installer 1.11, but I get the following error:

```
root@gattaca:/etc/foreman# foreman-installer --enable-foreman-plugin-memcache
ERROR: Unrecognised option '--enable-foreman-plugin-memcache'

See: 'foreman-installer --help'
```

Foreman-installer --help indeed does not list the plugin, but the Foreman 1.11 manual lists the plugin as being available. Did something change or am I just too tired and screwing something up?

**Comment by mmoll** [comment]
Since https://github.com/theforeman/puppet-foreman/commit/4a380942902f3e12d48c0c51589651a16cff0c54 this should work. On my system (nightly instraller):
```
# foreman-installer --full-help|grep memcache
    --[no-]enable-foreman-plugin-memcache Enable 'foreman_plugin_memcache' puppet module (default: false)
= Module foreman_plugin_memcache:
    --foreman-plugin-memcache-compress  will gzip-compress values larger than 1K (default: true)
    --foreman-plugin-memcache-expires-in  global default for key TTL in seconds (default: 86400)
    --foreman-plugin-memcache-hosts  an array of hosts running memcache (default: [])
    --foreman-plugin-memcache-namespace  prepends each key with this value to provide simple namespacing (default: "foreman")
```

**Comment by HyperBaton** [comment]
Strange... I've got 1.11.1-1 installed:

```
root@gattaca:/home/hb# foreman-installer --full-help | grep memcache
root@gattaca:/home/hb# dpkg -l | grep foreman-installer
ii  foreman-installer                1.11.1-1                     all          Automated puppet-based installer for The Foreman
root@gattaca:/home/hb# 
```

**Comment by mmoll** [comment]
```
  :foreman::plugin::memcache:
    :dir_name: foreman
    :manifest_name: plugin/memcache
    :params_name: plugin/memcache/params
```
has to be in the installer's .yaml file (I don't have a 1.11 install handy, but it's somewhere under /etc/foreman, iirc), if you updated your install and didn't overwrite that conf file with the new version, you won't have it in the installer.

**Comment by HyperBaton** [comment]
Aaah. Okay I'll check that out and get back to you. Good to know.

**Comment by HyperBaton** [comment]
Hey Michael, I forgot to close this one after confirming this, apologies.
